version: "3.9"

services:
  db:
    image: postgres:16
    container_name: booktok_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./booktok/db:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@booktok.com
      PGADMIN_DEFAULT_PASSWORD: smartbooktokadmin
    ports:
      - "5050:80"

volumes:
  db_data: {}
